import random
aa = str(round(random.random() * 10000000000000))
a ="JD" +  aa
# M 一等座
data_2 = {
    "retailOrderId": a,
    "fromStationCode": "BTC",
    "fromStationName": "包头",
    "toStationCode": "BDC",
    "toStationName": "包头东",
    "trainDate": "2018-02-30",
    "hasSeat": True,
    "passengers": [
        {
            "passengerId": 1,
            "ticketNo": None,
            "passengerName": "途牛测试单",
            "passengerSex": None,
            "passengerBirthday": None,
            "passportNo": "321181199112253533",
            "passportTypeId": "1",
            "passportTypeName": "身份证",
            "zwCode": "8",
            "zwName": "硬座",
            "cxin": None,
            "price": "86.50",
            "procedureFee": None,
            "reason": "0",
            "provinceCode": None,
            "schoolCode": None,
            "schoolName": None,
            "studentNo": None,
            "schoolSystem": None,
            "enterYear": None,
            "preferenceFromStationName": None,
            "preferenceFromStationCode": None,
            "preferenceToStationName": None,
            "preferenceToStationCode": None,
            "memo": None,
            "childName": None,
            "childBirthday": None,
            "childSex": None,
            "orderNumber": None,
            "piaoType": "1",
            "piaoTypeName": "成人票"
        },{
            "passengerId": 2,
            "ticketNo": None,
            "passengerName": "途牛测试单",
            "passengerSex": None,
            "passengerBirthday": None,
            "passportNo": "321181199112253534",
            "passportTypeId": "1",
            "passportTypeName": "身份证",
            "zwCode": "M",
            "zwName": "一等座",
            "cxin": None,
            "price": "86.50",
            "procedureFee": None,
            "reason": "0",
            "provinceCode": None,
            "schoolCode": None,
            "schoolName": None,
            "studentNo": None,
            "schoolSystem": None,
            "enterYear": None,
            "preferenceFromStationName": None,
            "preferenceFromStationCode": None,
            "preferenceToStationName": None,
            "preferenceToStationCode": None,
            "memo": None,
            "childName": None,
            "childBirthday": None,
            "childSex": None,
            "orderNumber": None,
            "piaoType": "1",
            "piaoTypeName": "成人票"
        }
    ],
    "contact": "邢毅勋",
    "phone": "15295115732",
    "userName": None,
    "userPassword": None,
    "insureCode": None,
    "bookType": 0,
    "reserveCheCi": None,
    "reserveZwCode": None,
    "deliveryInfo": None,
    "reservedTrainList": [
        {
            "fromStationCode": "JLL",
            "fromStationName": "吉林",
            "toStationCode": "DHL",
            "toStationName": "敦化",
            "seatType": "O",
            "trainDate": "2018-02-12",
            "trainNum": "C1025",
            "rank": 1
        }
    ],
    "transformFlag": None,
    "departDepartTime": None,
    "destArriveTime": None,
    "isTicketMonitor": 0,
    "paymentAccount": None,
    "cheCi": "C1025",
    "callBackUrl": "http://train.callback.jd.com/tuniu//callback_20009.html",
}

#保险：6636851000474    66368291
data_1 = {
    "retailOrderId": a,
    "fromStationCode": "BTC",
    "fromStationName": "包头",
    "toStationCode": "BDC",
    "toStationName": "包头东",
    "trainDate": "2018-02-06",
    "hasSeat": True,
    "passengers": [
        {
            "passengerId": 1,
            "ticketNo": None,
            "passengerName": "陈术",
            "passengerSex": None,
            "passengerBirthday": None,
            "passportNo": "32118119911225353X",
            "passportTypeId": "1",
            "passportTypeName": "身份证",
            "zwCode": "1",
            "zwName": "硬座",
            "cxin": None,
            "price": "6.00",
            "procedureFee": None,
            "reason": "0",
            "provinceCode": None,
            "schoolCode": None,
            "schoolName": None,
            "studentNo": None,
            "schoolSystem": None,
            "enterYear": None,
            "preferenceFromStationName": None,
            "preferenceFromStationCode": None,
            "preferenceToStationName": None,
            "preferenceToStationCode": None,
            "memo": None,
            "childName": None,
            "childBirthday": None,
            "childSex": None,
            "orderNumber": None,
            "piaoType": "1",
            "piaoTypeName": "成人票"
        }
    ],
    "contact": "邢毅勋",
    "phone": "15295115732",
    "userName": None,
    "userPassword": None,
    "insureCode": 6636851000462,
    "bookType": 0,
    "reserveCheCi": None,
    "reserveZwCode": None,
    "deliveryInfo": None,
    "reservedTrainList": [ ],
    "transformFlag": None,
    "departDepartTime": None,
    "destArriveTime": None,
    "isTicketMonitor": 0,
    "paymentAccount": None,
    "cheCi": "2636",
    "callBackUrl": "http://train.callback.jd.com/tuniu//callback_20009.html",
}